### ISSUE TITLE
Legibility

### ISSUE THREAD

**Issue by NathanDagDane** [LiamPalmqvist/NutButton#16]
Almost all instances of text use the same weight, size, and colour/opacity. This can significantly reduce legibility in various parts of the app; the most extreme case being on the history view:
<img src="https://github.com/user-attachments/assets/ac248486-eeab-4789-844a-bca927c97f6c" width="200">

This is the same view in 2 styles with varying font settings:
<img src="https://github.com/user-attachments/assets/1290cc82-83b1-42b5-aeb8-5e25966cce08" width="200"> <img src="https://github.com/user-attachments/assets/d0c1c601-7e41-4a7d-a715-1147d3b1a69c" width="200">

**Comment by LiamPalmqvist** [comment]
Closed with commit https://github.com/LiamPalmqvist/NutButton/commit/139cbd9425c705eb59e03eac22dac26caa2abb05
