### ISSUE TITLE
History Layout Problems

### ISSUE THREAD

**Issue by NathanDagDane** [LiamPalmqvist/NutButton#18]
On the 'number' layout view, the long date can wrap to another line: (also wait whats happening with the months??)
<br />
<img src="https://github.com/user-attachments/assets/37bf19f2-cbd7-4b13-83ca-6637a49f2b45" width="200">
<br />
On the 'short' view, the day number is aligned to the left, this may be intended and thats fine, but consider aligning the centres of all day numbers.
The time, however, is also aligned to the left after the day number, meaning they are offset left by largely varying amounts, making it unpleasant to read when scrolling. (On the same note, the year in the heading could be moved to before the month, so, when scrolling, the user can look out for the year without it jumping sideways as the month name length varies)
There is also a space between each box in only this mode.
<br />
<img src="https://github.com/user-attachments/assets/abceabf5-4620-4272-bf11-5685706ffc7c" width="200">
<br />
On the 'short' option there is potential to also shrink the height of the boxes, giving reason to choose the mode, as more information can be seen easier.

Lastly, in all modes, only the first month heading has changed its format.
A satisfying way to reformat these would be to significantly reduce the font size (-20 to 30%), reduce its opacity, and give it a higher weight. (Currently all text has the same weight and it can be difficult to discern the significance of each element).

**Comment by LiamPalmqvist** [comment]
Fixed formatting and other similar issues in commit https://github.com/LiamPalmqvist/NutButton/commit/7a7b43fcbc9b9889982bb6835181fbd2c40c80c2

**Comment by LiamPalmqvist** [comment]
Font is yet to be changed, I can't really do much about that right now without manually editing the font
