### ISSUE TITLE
Confirmation Dialogues

### ISSUE THREAD

**Issue by NathanDagDane** [LiamPalmqvist/NutButton#2]
Right now you can click reset/undo/import and it will do the action before any confirmation which could cause some bad accidents. There should definitely be some popup for these.
For the import, it should just ask what to do with duplicates (if found).

**Comment by LiamPalmqvist** [comment]
Closed and completed as of https://github.com/LiamPalmqvist/NutButton/commit/4e9c6d7b7dc17c9441cff2667ec24b8a24357015
