### ISSUE TITLE
Nut Button Delay

### ISSUE THREAD

**Issue by NathanDagDane** [LiamPalmqvist/NutButton#25]
There is a delay when tapping the nut button, appearing to be linked to when the finger lifts off from the screen, as the delay is very noticeable on very quick taps, and when lifting up the finger from a long tap.

**Comment by LiamPalmqvist** [comment]
partially closed in commit https://github.com/LiamPalmqvist/NutButton/commit/9939c8510e98910a266984919313b1a90cda1c1d
