### ISSUE TITLE
Light/Dark Selection on Launch

### ISSUE THREAD

**Issue by NathanDagDane** [LiamPalmqvist/NutButton#29]
Manual light/dark selection overrides the automatic option on launch

**Comment by LiamPalmqvist** [comment]
Closed as of commit https://github.com/LiamPalmqvist/NutButton/commit/9995685acfbd182f87874c8061d7248a17e5b075 in branch [WidgetKit_Integration](https://github.com/LiamPalmqvist/NutButton/tree/WidgetKit_Integration)
