### ISSUE TITLE
Home Sreen Menu

### ISSUE THREAD

**Issue by NathanDagDane** [LiamPalmqvist/NutButton#8]
The arrow is confusing, as it could be mistaken for a play button for less experienced users.

The icons in the dropdown are confusing for those same users, who would require a universal menu icon (3 dots or 3 line stack) which opens to a menu containing text headings.

**Comment by LiamPalmqvist** [comment]
Fixed as of commit https://github.com/LiamPalmqvist/NutButton/commit/2471f2068fa00c745fea6e562986d70c22cc7493
